name: task-vectors
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.9.24=ha878542_0
  - cffi=1.15.1=py310h74dc2b5_0
  - cryptography=37.0.2=py310h597c629_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310ha2c4b55_0
  - mkl_fft=1.3.1=py310h2b4bcf5_1
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - numpy-base=1.23.1=py310hcba007f_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1o=h166bdaf_0
  - pip=22.2.2=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - python_abi=3.10=2_cp310
  - pytorch=1.12.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py310h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022c=h04d1e81_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - contourpy==1.0.5
    - cvxpy==1.2.2
    - cycler==0.11.0
    - ecos==2.0.10
    - filelock==3.8.0
    - fonttools==4.37.4
    - ftfy==6.1.1
    - huggingface-hub==0.10.0
    - idna==3.4
    - kiwisolver==1.4.4
    - matplotlib==3.6.0
    - numpy==1.23.3
    - open-clip-torch==2.0.2
    - osqp==0.6.2.post5
    - packaging==21.3
    - pandas==1.5.0
    - patsy==0.5.2
    - pillow==9.2.0
    - plotly==5.11.0
    - pycparser==2.21
    - pyopenssl==22.0.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyyaml==6.0
    - qdldl==0.1.5.post2
    - regex==2022.9.13
    - requests==2.28.1
    - scipy==1.9.1
    - scs==3.2.2
    - seaborn==0.12.1
    - six==1.16.0
    - statsmodels==0.13.2
    - tenacity==8.1.0
    - torch==1.12.1
    - torchaudio==0.12.1+cu116
    - torchvision==0.13.1
    - tqdm==4.64.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - wheel==0.37.1
